/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 src/assets/hegra/scene.gltf -p 
Author: LibanCiel (https://sketchfab.com/LibanCiel)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/al-ula-ksa-dc715d68ad04422e816b6f3abdc843c8
Title: Al Ula, KSA العلا
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.524, -22.559]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model_1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model_2} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model_3} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model_4} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Model_5} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Model_6} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Model_7} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Model_8} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Model_9} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
